backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "homepage"
        label: "Homepage Config"
        file: "homepage.json"
        description: "Homepage settings"
        fields:
          - label: "Homepage image"
            name: "home_image"
            widget: "image"
            choose_url: true
            media_library:
              config:
                multiple: true
          - label: "Body"
            name: "body"
            widget: "markdown"

      - name: "videos_page"
        label: "Videos Page Config"
        file: "videos.json"
        description: "Videos page settings"
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
          - label: "video links"
            name: "video_urls"
            widget: "list"
            summary: "{{fields.description}} {{fields.url}}"
            fields:
              - label: URL
                name: url
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "markdown"

      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"
          - label: "Navigation Links"
            name: "navigation_links"
            widget: "list"
            summary: "{{fields.name}} {{fields.url}}"
            fields:
              - label: Name
                name: name
                widget: "string"
              - label: URL
                name: url
                widget: "string"

  - name: "pages"
    label: "Pages"
    folder: "content/pages/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
